export const MAIN_LABEL = 'Football Formations Page';
export const HEADER_LABEL = 'Football Formations Header';
export const FOOTBALL_FORMATIONS_HEADING = 'Football Formations';
export const FOOTBALL_FORMATIONS_SUBHEADING = 'An accessible demo app to view different football formations';
export const FORMATION_SELECTION_SECTION_LABEL = 'Formation Selection Section';
export const FORMATIONS_SELECT_LABEL = 'Select formation';
export const NO_FORMATION = 'None';
export const FORMATIONS = ['4-4-2', '3-4-2', '5-2-3'];
export const FORMATION_DISPLAY_SECTION_LABEL = 'Formation Display Section';
